version: '3.9'
services:
  db:
    image: mysql:8.0.32
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: 40446610
      MYSQL_USER: docker
      MYSQL_PASSWORD: 40446610
      MYSQL_DATABASE: rest_with_spring_boot_igor
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    ports:
      - 3308:3308
    expose:
      - 3308
    networks:
      - igor-network
  rest-with-spring-boot-igor:
    image: igoralves56/rest-with-spring-boot-igor
    restart: always
    working_dir: /05_FirstStepsinJavawithSpringBoot
    environment:
      TZ: America/Sao_paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://db:3308/rest_with_spring_boot_igor?useTimezone=true&serverTimezone=UTC
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: 40446610
    ports:
      - 80:80
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - igor-network
networks: 
  igor-network:
    driver: bridge